name: continuous integration example
on:
  push:
    branches:
      main
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Build with gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Run tests
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew test

  run-system-tests:
    runs-on: self-hosted
    needs: build-and-test

    steps:
      - uses: actions/checkout@v1

      - name: Run the server
        working-directory: .
        run: |
          chmod +x gradlew
          docker-compose up --build -d

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: Run system test
        working-directory: .
        run: pytest

      - name: Stop the server
        working-directory: .
        run: docker-compose down

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Copy repo to cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSWORD }}
          source: "./"
          target: "~/prod"
      - name: Restart All Instances on Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSWORD }}
          script: |
            cd ~/prod
            docker-compose down && docker-compose up --build -d